name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - name: Install valgrind
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: |
            sudo apt update
            sudo apt install -f valgrind -y
      - name: zig build & run
        run: zig build run -Doptimize=ReleaseFast
      - name: Valgrind test
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: time valgrind --leak-check=full zig-out/bin/example


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check --ast-check **.zig
